/* soapTMSServiceSoapProxy.h
   Generated by gSOAP 2.8.19 from d:\CimsForTa\TmsServer\TmsServer.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapTMSServiceSoapProxy_H
#define soapTMSServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC TMSServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'TMSServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in d:\CimsForTa\TmsServer\TmsServer.h (non-static)
	/// Constructor
	TMSServiceSoapProxy();
	/// Construct from another engine state
	TMSServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	TMSServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	TMSServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	TMSServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	TMSServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~TMSServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void TMSServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'loginUser' (returns error code or SOAP_OK)
	virtual	int loginUser(_ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse) { return this->loginUser(NULL, NULL, ns1__loginUser, ns1__loginUserResponse); }
	virtual	int loginUser(const char *endpoint, const char *soap_action, _ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse);

	/// Web service operation 'logoutUser' (returns error code or SOAP_OK)
	virtual	int logoutUser(_ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse) { return this->logoutUser(NULL, NULL, ns1__logoutUser, ns1__logoutUserResponse); }
	virtual	int logoutUser(const char *endpoint, const char *soap_action, _ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse);

	/// Web service operation 'QueryObjects' (returns error code or SOAP_OK)
	virtual	int QueryObjects(_ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse) { return this->QueryObjects(NULL, NULL, ns1__QueryObjects, ns1__QueryObjectsResponse); }
	virtual	int QueryObjects(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse);

	/// Web service operation 'GetObjectsVersion' (returns error code or SOAP_OK)
	virtual	int GetObjectsVersion(_ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse) { return this->GetObjectsVersion(NULL, NULL, ns1__GetObjectsVersion, ns1__GetObjectsVersionResponse); }
	virtual	int GetObjectsVersion(const char *endpoint, const char *soap_action, _ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse);

	/// Web service operation 'DownloadFileById' (returns error code or SOAP_OK)
	virtual	int DownloadFileById(_ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse) { return this->DownloadFileById(NULL, NULL, ns1__DownloadFileById, ns1__DownloadFileByIdResponse); }
	virtual	int DownloadFileById(const char *endpoint, const char *soap_action, _ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse);

	/// Web service operation 'SaveOrUpdateObjects' (returns error code or SOAP_OK)
	virtual	int SaveOrUpdateObjects(_ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse) { return this->SaveOrUpdateObjects(NULL, NULL, ns1__SaveOrUpdateObjects, ns1__SaveOrUpdateObjectsResponse); }
	virtual	int SaveOrUpdateObjects(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse);

	/// Web service operation 'DeleteObject' (returns error code or SOAP_OK)
	virtual	int DeleteObject(_ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse) { return this->DeleteObject(NULL, NULL, ns1__DeleteObject, ns1__DeleteObjectResponse); }
	virtual	int DeleteObject(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse);

	/// Web service operation 'loginUser' (returns error code or SOAP_OK)
	virtual	int loginUser_(_ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse) { return this->loginUser_(NULL, NULL, ns1__loginUser, ns1__loginUserResponse); }
	virtual	int loginUser_(const char *endpoint, const char *soap_action, _ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse);

	/// Web service operation 'logoutUser' (returns error code or SOAP_OK)
	virtual	int logoutUser_(_ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse) { return this->logoutUser_(NULL, NULL, ns1__logoutUser, ns1__logoutUserResponse); }
	virtual	int logoutUser_(const char *endpoint, const char *soap_action, _ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse);

	/// Web service operation 'QueryObjects' (returns error code or SOAP_OK)
	virtual	int QueryObjects_(_ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse) { return this->QueryObjects_(NULL, NULL, ns1__QueryObjects, ns1__QueryObjectsResponse); }
	virtual	int QueryObjects_(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse);

	/// Web service operation 'GetObjectsVersion' (returns error code or SOAP_OK)
	virtual	int GetObjectsVersion_(_ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse) { return this->GetObjectsVersion_(NULL, NULL, ns1__GetObjectsVersion, ns1__GetObjectsVersionResponse); }
	virtual	int GetObjectsVersion_(const char *endpoint, const char *soap_action, _ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse);

	/// Web service operation 'DownloadFileById' (returns error code or SOAP_OK)
	virtual	int DownloadFileById_(_ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse) { return this->DownloadFileById_(NULL, NULL, ns1__DownloadFileById, ns1__DownloadFileByIdResponse); }
	virtual	int DownloadFileById_(const char *endpoint, const char *soap_action, _ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse);

	/// Web service operation 'SaveOrUpdateObjects' (returns error code or SOAP_OK)
	virtual	int SaveOrUpdateObjects_(_ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse) { return this->SaveOrUpdateObjects_(NULL, NULL, ns1__SaveOrUpdateObjects, ns1__SaveOrUpdateObjectsResponse); }
	virtual	int SaveOrUpdateObjects_(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse);

	/// Web service operation 'DeleteObject' (returns error code or SOAP_OK)
	virtual	int DeleteObject_(_ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse) { return this->DeleteObject_(NULL, NULL, ns1__DeleteObject, ns1__DeleteObjectResponse); }
	virtual	int DeleteObject_(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse);
};
#endif
