/* soapTMSServiceSoapProxy.cpp
   Generated by gSOAP 2.8.19 from d:\CimsForTa\TmsServer\TmsServer.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapTMSServiceSoapProxy.h"

TMSServiceSoapProxy::TMSServiceSoapProxy()
{	TMSServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

TMSServiceSoapProxy::TMSServiceSoapProxy(const struct soap &_soap) : soap(_soap)
{ }

TMSServiceSoapProxy::TMSServiceSoapProxy(const char *url)
{	TMSServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

TMSServiceSoapProxy::TMSServiceSoapProxy(soap_mode iomode)
{	TMSServiceSoapProxy_init(iomode, iomode);
}

TMSServiceSoapProxy::TMSServiceSoapProxy(const char *url, soap_mode iomode)
{	TMSServiceSoapProxy_init(iomode, iomode);
	soap_endpoint = url;
}

TMSServiceSoapProxy::TMSServiceSoapProxy(soap_mode imode, soap_mode omode)
{	TMSServiceSoapProxy_init(imode, omode);
}

TMSServiceSoapProxy::~TMSServiceSoapProxy()
{ }

void TMSServiceSoapProxy::TMSServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://xerofox.com/TMSService/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void TMSServiceSoapProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void TMSServiceSoapProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	TMSServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void TMSServiceSoapProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *TMSServiceSoapProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *TMSServiceSoapProxy::soap_fault()
{	return this->fault;
}

const char *TMSServiceSoapProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *TMSServiceSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int TMSServiceSoapProxy::soap_close_socket()
{	return soap_closesock(this);
}

int TMSServiceSoapProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void TMSServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void TMSServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *TMSServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int TMSServiceSoapProxy::loginUser(const char *endpoint, const char *soap_action, _ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse)
{	struct soap *soap = this;
	struct __ns1__loginUser soap_tmp___ns1__loginUser;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/loginUser";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__loginUser.ns1__loginUser = ns1__loginUser;
	soap_serializeheader(soap);
	soap_serialize___ns1__loginUser(soap, &soap_tmp___ns1__loginUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__loginUser(soap, &soap_tmp___ns1__loginUser, "-ns1:loginUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__loginUser(soap, &soap_tmp___ns1__loginUser, "-ns1:loginUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__loginUserResponse)
		return soap_closesock(soap);
	ns1__loginUserResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__loginUserResponse.soap_get(soap, "ns1:loginUserResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::logoutUser(const char *endpoint, const char *soap_action, _ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse)
{	struct soap *soap = this;
	struct __ns1__logoutUser soap_tmp___ns1__logoutUser;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/logoutUser";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__logoutUser.ns1__logoutUser = ns1__logoutUser;
	soap_serializeheader(soap);
	soap_serialize___ns1__logoutUser(soap, &soap_tmp___ns1__logoutUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__logoutUser(soap, &soap_tmp___ns1__logoutUser, "-ns1:logoutUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__logoutUser(soap, &soap_tmp___ns1__logoutUser, "-ns1:logoutUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__logoutUserResponse)
		return soap_closesock(soap);
	ns1__logoutUserResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__logoutUserResponse.soap_get(soap, "ns1:logoutUserResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::QueryObjects(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse)
{	struct soap *soap = this;
	struct __ns1__QueryObjects soap_tmp___ns1__QueryObjects;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/QueryObjects";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__QueryObjects.ns1__QueryObjects = ns1__QueryObjects;
	soap_serializeheader(soap);
	soap_serialize___ns1__QueryObjects(soap, &soap_tmp___ns1__QueryObjects);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__QueryObjects(soap, &soap_tmp___ns1__QueryObjects, "-ns1:QueryObjects", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__QueryObjects(soap, &soap_tmp___ns1__QueryObjects, "-ns1:QueryObjects", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__QueryObjectsResponse)
		return soap_closesock(soap);
	ns1__QueryObjectsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__QueryObjectsResponse.soap_get(soap, "ns1:QueryObjectsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::GetObjectsVersion(const char *endpoint, const char *soap_action, _ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse)
{	struct soap *soap = this;
	struct __ns1__GetObjectsVersion soap_tmp___ns1__GetObjectsVersion;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/GetObjectsVersion";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObjectsVersion.ns1__GetObjectsVersion = ns1__GetObjectsVersion;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObjectsVersion(soap, &soap_tmp___ns1__GetObjectsVersion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObjectsVersion(soap, &soap_tmp___ns1__GetObjectsVersion, "-ns1:GetObjectsVersion", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObjectsVersion(soap, &soap_tmp___ns1__GetObjectsVersion, "-ns1:GetObjectsVersion", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetObjectsVersionResponse)
		return soap_closesock(soap);
	ns1__GetObjectsVersionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectsVersionResponse.soap_get(soap, "ns1:GetObjectsVersionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::DownloadFileById(const char *endpoint, const char *soap_action, _ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse)
{	struct soap *soap = this;
	struct __ns1__DownloadFileById soap_tmp___ns1__DownloadFileById;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/DownloadFileById";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DownloadFileById.ns1__DownloadFileById = ns1__DownloadFileById;
	soap_serializeheader(soap);
	soap_serialize___ns1__DownloadFileById(soap, &soap_tmp___ns1__DownloadFileById);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DownloadFileById(soap, &soap_tmp___ns1__DownloadFileById, "-ns1:DownloadFileById", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DownloadFileById(soap, &soap_tmp___ns1__DownloadFileById, "-ns1:DownloadFileById", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__DownloadFileByIdResponse)
		return soap_closesock(soap);
	ns1__DownloadFileByIdResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DownloadFileByIdResponse.soap_get(soap, "ns1:DownloadFileByIdResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::SaveOrUpdateObjects(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse)
{	struct soap *soap = this;
	struct __ns1__SaveOrUpdateObjects soap_tmp___ns1__SaveOrUpdateObjects;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/SaveOrUpdateObjects";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SaveOrUpdateObjects.ns1__SaveOrUpdateObjects = ns1__SaveOrUpdateObjects;
	soap_serializeheader(soap);
	soap_serialize___ns1__SaveOrUpdateObjects(soap, &soap_tmp___ns1__SaveOrUpdateObjects);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SaveOrUpdateObjects(soap, &soap_tmp___ns1__SaveOrUpdateObjects, "-ns1:SaveOrUpdateObjects", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SaveOrUpdateObjects(soap, &soap_tmp___ns1__SaveOrUpdateObjects, "-ns1:SaveOrUpdateObjects", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__SaveOrUpdateObjectsResponse)
		return soap_closesock(soap);
	ns1__SaveOrUpdateObjectsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SaveOrUpdateObjectsResponse.soap_get(soap, "ns1:SaveOrUpdateObjectsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::DeleteObject(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse)
{	struct soap *soap = this;
	struct __ns1__DeleteObject soap_tmp___ns1__DeleteObject;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/DeleteObject";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteObject.ns1__DeleteObject = ns1__DeleteObject;
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject, "-ns1:DeleteObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject, "-ns1:DeleteObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__DeleteObjectResponse)
		return soap_closesock(soap);
	ns1__DeleteObjectResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DeleteObjectResponse.soap_get(soap, "ns1:DeleteObjectResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::loginUser_(const char *endpoint, const char *soap_action, _ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse)
{	struct soap *soap = this;
	struct __ns1__loginUser_ soap_tmp___ns1__loginUser_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/loginUser";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__loginUser_.ns1__loginUser = ns1__loginUser;
	soap_serializeheader(soap);
	soap_serialize___ns1__loginUser_(soap, &soap_tmp___ns1__loginUser_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__loginUser_(soap, &soap_tmp___ns1__loginUser_, "-ns1:loginUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__loginUser_(soap, &soap_tmp___ns1__loginUser_, "-ns1:loginUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__loginUserResponse)
		return soap_closesock(soap);
	ns1__loginUserResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__loginUserResponse.soap_get(soap, "ns1:loginUserResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::logoutUser_(const char *endpoint, const char *soap_action, _ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse)
{	struct soap *soap = this;
	struct __ns1__logoutUser_ soap_tmp___ns1__logoutUser_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/logoutUser";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__logoutUser_.ns1__logoutUser = ns1__logoutUser;
	soap_serializeheader(soap);
	soap_serialize___ns1__logoutUser_(soap, &soap_tmp___ns1__logoutUser_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__logoutUser_(soap, &soap_tmp___ns1__logoutUser_, "-ns1:logoutUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__logoutUser_(soap, &soap_tmp___ns1__logoutUser_, "-ns1:logoutUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__logoutUserResponse)
		return soap_closesock(soap);
	ns1__logoutUserResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__logoutUserResponse.soap_get(soap, "ns1:logoutUserResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::QueryObjects_(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse)
{	struct soap *soap = this;
	struct __ns1__QueryObjects_ soap_tmp___ns1__QueryObjects_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/QueryObjects";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__QueryObjects_.ns1__QueryObjects = ns1__QueryObjects;
	soap_serializeheader(soap);
	soap_serialize___ns1__QueryObjects_(soap, &soap_tmp___ns1__QueryObjects_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__QueryObjects_(soap, &soap_tmp___ns1__QueryObjects_, "-ns1:QueryObjects", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__QueryObjects_(soap, &soap_tmp___ns1__QueryObjects_, "-ns1:QueryObjects", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__QueryObjectsResponse)
		return soap_closesock(soap);
	ns1__QueryObjectsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__QueryObjectsResponse.soap_get(soap, "ns1:QueryObjectsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::GetObjectsVersion_(const char *endpoint, const char *soap_action, _ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse)
{	struct soap *soap = this;
	struct __ns1__GetObjectsVersion_ soap_tmp___ns1__GetObjectsVersion_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/GetObjectsVersion";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObjectsVersion_.ns1__GetObjectsVersion = ns1__GetObjectsVersion;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObjectsVersion_(soap, &soap_tmp___ns1__GetObjectsVersion_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObjectsVersion_(soap, &soap_tmp___ns1__GetObjectsVersion_, "-ns1:GetObjectsVersion", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObjectsVersion_(soap, &soap_tmp___ns1__GetObjectsVersion_, "-ns1:GetObjectsVersion", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetObjectsVersionResponse)
		return soap_closesock(soap);
	ns1__GetObjectsVersionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectsVersionResponse.soap_get(soap, "ns1:GetObjectsVersionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::DownloadFileById_(const char *endpoint, const char *soap_action, _ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse)
{	struct soap *soap = this;
	struct __ns1__DownloadFileById_ soap_tmp___ns1__DownloadFileById_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/DownloadFileById";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DownloadFileById_.ns1__DownloadFileById = ns1__DownloadFileById;
	soap_serializeheader(soap);
	soap_serialize___ns1__DownloadFileById_(soap, &soap_tmp___ns1__DownloadFileById_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DownloadFileById_(soap, &soap_tmp___ns1__DownloadFileById_, "-ns1:DownloadFileById", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DownloadFileById_(soap, &soap_tmp___ns1__DownloadFileById_, "-ns1:DownloadFileById", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__DownloadFileByIdResponse)
		return soap_closesock(soap);
	ns1__DownloadFileByIdResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DownloadFileByIdResponse.soap_get(soap, "ns1:DownloadFileByIdResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::SaveOrUpdateObjects_(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse)
{	struct soap *soap = this;
	struct __ns1__SaveOrUpdateObjects_ soap_tmp___ns1__SaveOrUpdateObjects_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/SaveOrUpdateObjects";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SaveOrUpdateObjects_.ns1__SaveOrUpdateObjects = ns1__SaveOrUpdateObjects;
	soap_serializeheader(soap);
	soap_serialize___ns1__SaveOrUpdateObjects_(soap, &soap_tmp___ns1__SaveOrUpdateObjects_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SaveOrUpdateObjects_(soap, &soap_tmp___ns1__SaveOrUpdateObjects_, "-ns1:SaveOrUpdateObjects", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SaveOrUpdateObjects_(soap, &soap_tmp___ns1__SaveOrUpdateObjects_, "-ns1:SaveOrUpdateObjects", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__SaveOrUpdateObjectsResponse)
		return soap_closesock(soap);
	ns1__SaveOrUpdateObjectsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SaveOrUpdateObjectsResponse.soap_get(soap, "ns1:SaveOrUpdateObjectsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int TMSServiceSoapProxy::DeleteObject_(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse)
{	struct soap *soap = this;
	struct __ns1__DeleteObject_ soap_tmp___ns1__DeleteObject_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:801/TmsService.asmx";
	if (soap_action == NULL)
		soap_action = "http://xerofox.com/TMSService/DeleteObject";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteObject_.ns1__DeleteObject = ns1__DeleteObject;
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteObject_(soap, &soap_tmp___ns1__DeleteObject_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteObject_(soap, &soap_tmp___ns1__DeleteObject_, "-ns1:DeleteObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteObject_(soap, &soap_tmp___ns1__DeleteObject_, "-ns1:DeleteObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__DeleteObjectResponse)
		return soap_closesock(soap);
	ns1__DeleteObjectResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DeleteObjectResponse.soap_get(soap, "ns1:DeleteObjectResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
