//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapLds.rc
//
#define ID_APPLY                        3
#define IDC_BN_IMPORT_TXT_FILE          3
#define IDC_BN_IMPORT_EXCEL_FILE        4
#define IDC_BN_EMPTY_DATA               5
#define IDC_BTN_CREATE_CUR_PART         9
#define IDC_BTN_BATCH_CREATE            10
#define IDS_PROJNAME                    100
#define IDS_PROPSHT_CAPTION             101
#define IDD_STRU_MAP_PROPPAGE           103
#define IDD_PART_MAP_PROPPAGE           104
#define IDD_GENERAL_INPUT_DLG           131
#define IDD_PUTMESSAGE_DLG              132
#define IDC_ARROW_LINE_END              132
#define IDC_ARROW_POINT                 133
#define IDD_TALK_BOX_DLG                134
#define IDC_ARROW_LINE                  134
#define IDC_ARROW_DRAG_COPY             135
#define IDC_ARROW_DRAG_LINK             136
#define IDC_ARROW_DRAG_MOVE             137
#define IDC_ARROW_OSNAP                 140
#define IDD_MAP_SCALE                   142
#define IDC_ARROW_CIRCLE                142
#define IDD_SEL_MAP_SEG                 143
#define IDC_ARROW_RECT                  143
#define IDD_FILE_PROPERTY_DLG           147
#define IDC_DRAW_PENCIL                 148
#define IDC_DRAW_CROSS                  149
#define IDC_DRAW_ARROW_PENCIL           150
#define IDD_SET_ACTIVE_MODULE_DLG       151
#define IDC_DRAW_CROSS_REC              151
#define IDD_SIZE_DIMENSION              152
#define IDC_ARROW_LINK                  152
#define IDD_SYS_SET_DLG                 168
#define IDD_MXB_DLG                     169
#define IDD_INPUT_PART_CODE_DLG         175
#define IDD_DEF_NODE_FACE_VERTEX_DLG    177
#define IDD_INPUT_WORK_NORM_DLG         178
#define IDD_DECARL_TO_POLAR_DLG         180
#define IDD_TEXT_AND_DIM_PROPPAGE       182
#define IDD_PEN_COLOR_PAGE              183
#define IDD_INPUT_AN_VAL_DLG            186
#define IDD_INPUT_AN_INTEGER_VAL_DLG    186
#define IDI_KEY                         187
#define IDI_SERVER                      188
#define IDI_USER                        189
#define IDD_SET_MAP_SCALE_DLG           200
#define IDD_LOAD_GRAPH_DLG              201
#define IDC_E_HOLE_AUGMENT              202
#define IDC_E_JG_CARD_PATH              203
#define IDD_BACK_MIR_STYLE_DLG          203
#define IDC_E_ANGLE_CARD_PATH           203
#define IDC_BN_LOCATE_JG_CARD           204
#define IDD_DIM_SIMPOLY_CFG_DLG         204
#define IDC_E_DISPLAY_CONTENT           205
#define IDC_E_TUBE_CARD_PATH            205
#define IDC_E_WELD_PART_GROUP_CARD_PATH 205
#define IDC_E_TEXT_HIGH                 206
#define IDC_BN_LOCATE_TUBE_CARD         206
#define IDC_BN_LOCATE_WELD_PART_GROUP_CARD 206
#define IDC_E_RATIO_HTOW                207
#define IDC_BN_LOCATE_PLANK_CARD        207
#define IDC_RDO_ALIGN_TYPE              208
#define IDC_E_PLANK_CARD_PATH           208
#define IDC_RDO_ALIGN_TYPE2             209
#define IDC_VERTICAL                    209
#define IDC_E_PROCESS_PART_STAT_CARD_PATH 209
#define IDC_RDO_ALIGN_TYPE3             210
#define IDC_EXTEND                      210
#define IDD_DIM_SPACE_SIZE_DLG          210
#define IDC_BN_LOCATE_PROCESS_PART_STAT_CARD 210
#define IDC_RDO_X_ARROW                 210
#define IDC_RDO_ALIGN_TYPE4             211
#define IDC_E_CUR_MAPSCALE              211
#define IDC_RDO_ROW_FIRST               211
#define IDC_RDO_Y_ARROW                 211
#define IDC_RDO_ALIGN_TYPE5             212
#define IDC_E_FLOAT_PRECISION           212
#define IDC_RDO_MIR_AXIS_X              212
#define IDD_SEL_CUR_FACE_FLAG_DLG       212
#define IDC_RDO_Z_ARROW                 212
#define IDC_RDO_ALIGN_TYPE6             213
#define IDC_RDO_MIR_AXIS_Y              213
#define IDC_E_ROWS_OR_COLUMNS           213
#define IDC_RDO_ALIGN_TYPE7             214
#define IDC_RDO_MIR_AXIS_NONE           214
#define IDC_BN_MAP_DRAW_UCS             214
#define IDD_FOOT_VIEW_DLG               214
#define IDC_RDO_ALIGN_TYPE8             215
#define IDC_CHK_DIM_HUOQU_FACE          215
#define IDC_RDO_ALIGN_TYPE9             216
#define IDC_CHK_DIM_SPECIAL_LSSPACE     216
#define IDD_INSERT_MAP_FRAME_DLG        216
#define IDC_E_ROW_GAP                   216
#define IDC_CHK_DIM_SPECIAL_LSSPACE2    217
#define IDC_CHK_DIM_SPECIAL_JGZHUNJU    217
#define IDC_RDO_CUR_FACE                217
#define IDD_PLANK_PART_PARA_EXPORT_DLG  217
#define IDC_E_DISPLAY_PREFIX            217
#define IDC_RDO_CUR_FACE2               218
#define IDC_S_VAL_NAME                  218
#define IDC_CHK_DIM_STRU_DIM_JGLEN      218
#define IDC_E_COLUMN_GAP                218
#define IDC_E_DISPLAY_CONTENT3          218
#define IDC_E_DISPLAY_SUFFIX            218
#define IDC_RDO_CUR_FACE3               219
#define IDC_CHK_DRAW_REFLINE            219
#define IDC_E_FOOT_HANDLE               220
#define IDC_CHK_DIM_ONCE_ROUND_SAME_PART 220
#define IDC_RDO_VIEW_STYLE              221
#define IDD_SEL_CUR_FACE_DLG            221
#define IDC_RDO_VIEW_STYLE2             222
#define IDD_DRAWING_VECTOR_DLG          222
#define IDC_RDO_VIEW_STYLE3             223
#define IDD_PART_SET_CREATOR_DLG        223
#define IDC_RDO_VIEW_STYLE4             224
#define IDC_RDO_VIEW_STYLE5             225
#define IDC_E_DRAW_SCALE                226
#define IDD_PART_DRAWING_ARRAY_DLG      226
#define IDC_RDO_VIEW_STYLE6             227
#define IDC_RADIO5                      228
#define IDC_CHK_TA_TYPE                 228
#define IDC_RADIO6                      229
#define IDC_CHK_PART_NO                 229
#define IDD_TUBE_SPREAD_CURVE_EXPORT_DLG 229
#define IDC_RADIO7                      230
#define IDC_CHK_PLANK_THICK             230
#define IDC_CHK_CARD_LAYOUT_BASE_ROW    230
#define IDD_STAT_STD_PARTGROUP_DLG      230
#define IDC_CHK_PART_MAT                231
#define IDC_S_MAXROW_OR_COLUMN          231
#define IDC_CHK_PART_SIZE               232
#define IDC_CMB_SPECIAL_PARTMAP_RULE    232
#define IDC_CMB_PART_MAP_STYLE          232
#define IDD_SETUP_AIDED_PLATE_DLG       232
#define IDC_CHK_PIECE_WEIGHT            233
#define IDC_RDO_HOLE_LEN_DIM_PRECISION  233
#define IDD_PART_GROUP_PROPPAGE         233
#define IDC_CHK_SUM_WEIGHT              234
#define IDC_RADIO8                      234
#define IDC_DISPLAY_VIEW_LIST           234
#define IDD_CAL_TWO_TUBE_ANGLE_DLG      234
#define IDC_CHK_VERTEX_MARK             235
#define IDC_RADIO9                      235
#define IDC_SECTION_VIEW_LIST           235
#define IDC_CHK_PRJ_NAME                236
#define IDC_RDO_HOLE_RELATIVE_LEN_DIM_PRECISION 236
#define IDC_PART_GROUP_LIST             236
#define IDC_CHK_PRJ_CODE                237
#define IDC_RADIO11                     237
#define IDC_E_SEG_STR                   237
#define IDC_CHK_TOWER_ALIAS             237
#define IDC_RADIO12                     238
#define IDC_BN_REBUILD_PARTSET          238
#define IDC_LIST_EXPORT_PART_INFO       238
#define IDD_SYSTEM_SETTING_DLG          238
#define IDC_E_EDIT_LINE                 239
#define IDC_BN_ADD_PPI_FILE             239
#define IDC_BN_CLEAR_EDIT_LINE          240
#define IDD_STD_PART_SET_DLG            240
#define IDC_CHK_DIM_LS_SPACE            241
#define IDC_BN_ADD_EDIT_LINE            241
#define IDC_TREE_PART_GROUP             241
#define IDD_PART_DRAWING_PARA_DLG       241
#define IDC_CHK_DIM_LS_POS              242
#define IDC_BN_DEL_CURRENT_LINE         242
#define IDC_S_CURRENT_PART_GROUP        242
#define IDD_DRAW_MAP_SCRIPT_DLG         242
#define IDC_CHK_DIM_CUT_ANGLE           243
#define IDC_CHK_LS_NUM                  243
#define IDC_S_CURRENT_SECTION_VIEW      243
#define IDC_TREE_DISPLAY_VIEW           243
#define IDR_BAR_SCRIPT                  243
#define IDC_CHK_DIM_KAIHE               244
#define IDC_CHK_STAMP_NO                244
#define IDD_DEF_DRAWING_UCS_DLG         245
#define IDD_INPUT_DRAWING_UCS_DLG       245
#define IDC_CMB_LS_POS_STYLE            245
#define IDC_CHK_PART_NUM                245
#define IDC_RDO_SPECIAL_PROCESS_TYPE    245
#define IDR_MENU_SCRIPT                 245
#define IDD_INSERT_FRAME_DLG            246
#define IDC_CHK_PIECE_AREA              246
#define IDC_RADIO10                     246
#define IDC_CHK_INNER_SPREAD_CURVE      246
#define IDC_DIM_PLANK_BOLT_ANGLE        246
#define IDC_CURSOR1                     246
#define IDC_RDO_MAP_FRM                 247
#define IDC_RADIO13                     247
#define IDC_CHK_OUTTER_SPREAD_CURVE     247
#define IDC_CMB_START_PART_TYPE         247
#define IDC_CHK_DIM_CUT_ANGLE_MAP       247
#define IDC_CHK_TA_NUM                  247
#define IDC_RADIO14                     248
#define IDC_CHK_INNER_OUTTER_COMPOSE_SPREAD_CURVE 248
#define IDC_CMB_END_PART_TYPE           248
#define IDC_CHK_DIM_CUT_ANGLE_MAP2      248
#define IDC_CHK_DIM_KAIHE_ANGLE_MAP     248
#define IDR_CMD_POPUP                   248
#define IDD_SELECT_DRAWING_DLG          248
#define IDC_CHK_SUPPORT_TABLE           248
#define IDC_RADIO15                     249
#define IDC_CHK_STAT_ALL_TYPE           249
#define IDC_CHK_DIM_PUSH_FLAT_MAP       249
#define IDC_BN_ADD_ROW                  249
#define IDC_CHK_PROCESS_SPREAD_CURVE    249
#define IDC_CHK_IGNORE_STD_PARTGROUP    250
#define IDD_NEW_DRAWINGVIEW_DLG         250
#define IDC_BN_DEL_ROW                  250
#define IDC_E_AIDED_PLATE_FILE_PATH     251
#define IDC_BN_MOVE_UP                  251
#define IDC_BTN_BROWSE_FILE             252
#define IDD_ADD_VIEW                    252
#define IDC_BN_MOVE_DOWN                252
#define IDC_BTN_REBUILD_PARTSET         253
#define IDD_SET_PART_MAP_FILE_PATH_DLG  253
#define IDC_CHK_SUM_PART_NUM            253
#define IDC_CHK_MODULATE_PARTGROUP_LEN  254
#define IDD_IMPORT_SCRIPT_OPTION_DLG    254
#define IDC_CHK_HUOQU                   254
#define IDC_E_PARTGROUP_DIST_THRESHOLD  255
#define IDD_DIALOG1                     255
#define IDD_DRAW_UCS_DLG                255
#define IDC_CHK_WELD_PART               255
#define IDC_E_PARTGROUP_DIST_ZOOM_COEF  256
#define IDD_SUMTAMAT_TBL_CFG_DLG        256
#define IDC_CHK_SAVE_CONFIG             256
#define IDC_CHK_SAVE_CONFIG_FILE        256
#define IDC_CHK_DIM_SPACE_DIST          257
#define IDC_E_START_TUBE_HANDLE         257
#define IDR_SUM_MAT_CFG                 257
#define IDC_CHK_DIM_ABSOLUTE_DIST       258
#define IDC_E_END_TUBE_HANDLE           258
#define IDB_IL_PROJECT1                 258
#define IDB_IL_PROJECT                  258
#define IDC_CHK_USE_Y_ORDER             259
#define IDC_E_TUBE_ANGLE                259
#define IDD_SELECT_SIMPLE_SPEC_DLG      259
#define IDC_E_LAYER_SPACE               260
#define IDC_BTN_CAL_TWO_TUBE_ANGLE      260
#define IDD_BREAK_LINE_DLG              260
#define IDC_CHK_DIM_ABSOLUTE_OUTERMOST_LAYER 261
#define IDC_CHK_DIM_TUBE_ANGLE          261
#define IDD_ADD_NEW_LAYER_DLG           261
#define IDC_CHK_ANGULAR_DIMENSION       262
#define IDC_E_DIM_RADIUS                262
#define IDC_CHK_DIM_CHECK_LINE          263
#define IDC_CHK_INPUT_TUBE_HANDLE       263
#define IDC_CHK_DIM_AFTER_WELD_CHECK_LINE 263
#define IDD_ADJUST_PART_DRAWING_SERIALNO 263
#define IDC_S_PROMPT_STR                264
#define IDC_CHK_DIM_BEFORE_WELD_CHECK_LINE 264
#define IDD_NEW_MAP_FRAME_DLG           264
#define IDC_CHK_STD_PART                265
#define IDC_CHK_DIM_PLATE_POLE_RAYANDANGLE 265
#define IDC_CMB_START_TYPE              266
#define IDC_CHK_ADJUST_SCALE_BY_PROCESS_CARD 266
#define IDC_CHK_CREATE_TUBE_BRIEF       266
#define IDB_BMP_BODY_QUAD               266
#define IDC_CMB_END_TYPE                267
#define IDC_CHK_AUTO_DIM_PART_NO        267
#define IDC_CHK_CREATE_JG_CUTANGLE_BRIEF_MAP 267
#define IDC_CHK_ALL_SLOT                268
#define IDC_CHK_AUTO_MATCH_VIEW         268
#define IDC_CHK_PROCESS_PART            268
#define IDC_CMB_FONT_NAME               269
#define IDC_CHK_GROUP_BY_SEGI           269
#define IDC_CHK_POLAR_COORD             270
#define IDD_ADD_ANGLE_BY_REMOVE_NAIL_DLG 270
#define IDC_CHK_ONE_SEG_ONE_FILE        270
#define IDC_CHK_DECARL_COORD            271
#define IDD_INPUT_MK_RECT_DLG           271
#define IDC_DIM_PLATE_BOLT_ANGLE        272
#define IDC_DIM_PLATE_RAY_LS            273
#define IDD_TID_TO_DWG_DLG              273
#define IDC_CHK_DIM_PLATE_OUTLINE       274
#define IDD_POLY_JG_SET_DLG             274
#define IDC_E_PART_MAP_TYPE             275
#define IDD_EXPORT_SET_DLG              275
#define IDC_CMB_PART_MAP_TYPE           276
#define IDC_E_PROP_HELP_STR             278
#define IDC_TAB_GROUP                   279
#define IDC_E_CMD_HELP_STR              279
#define IDC_LIST_BOX                    280
#define IDC_BTN_OK                      281
#define IDC_BTN_CANCEL                  282
#define IDC_COMBO1                      283
#define IDC_CMB_PROFILE_STYLE           283
#define IDC_CMB_SEG                     283
#define IDC_CMB_COLOR                   283
#define IDC_CMB_SERIALNO                283
#define IDC_CMB_PLANK_AREA_STAT_TYPE2   283
#define IDC_CMB_TASK                    283
#define IDC_CMB_ROLL_TYPE               283
#define IDC_CMB_MODEL_LEVEL             283
#define IDC_CMB_TOWERTYPE               284
#define IDC_CMB_SEG_NO                  285
#define IDC_E_LIB_FILE_PATH             286
#define IDD_PROC_BAR_DLG                287
#define IDC_CHK_AUTO_ARRANGE_PLATE      287
#define IDC_E_MAP_W                     288
#define IDC_E_MINDISTANCE               289
#define IDC_S_PART_NUM                  290
#define IDC_E_MAP_L                     290
#define IDC_BTN_CLOSE                   295
#define IDC_TAB_CMD_TYPE                298
#define IDC_S_SCRIPT_NAME               304
#define IDC_E_KEY_WORD                  305
#define IDC_BUTTON1                     306
#define IDC_BN_DEL_VIEW                 306
#define IDC_BTN_MOVE_AFTER              306
#define IDC_BTN_SNAP_OBJ                306
#define IDC_BN_SPEC_WELDPART_CARD_PATHFILE 306
#define IDC_VIEW_LIST                   307
#define IDC_TREE_DRAWING                308
#define IDC_E_NAME                      309
#define IDC_E_NO                        310
#define IDC_LIST_SELECT_VIEW            312
#define IDC_LIST_REMAIN_VIEW            313
#define IDC_BN_ADD_VIEW                 314
#define IDC_BTN_SAVE_SCRIPT             316
#define IDC_BTN_DISPLAY_CMD_DLG         317
#define IDC_CHK_SUM_MAP                 318
#define IDC_CHK_CHIEF_MAP               319
#define IDC_E_DRAW_RECT_LEN             319
#define IDC_CHK_STRU_MAP                320
#define IDC_E_DRAW_RECT_WIDTH           320
#define IDC_CHK_PART_MAP                321
#define IDD_INPUT_AN_STRING_VAL_DLG     321
#define IDC_CHK_WELD_MAP                322
#define IDC_CHK_USE_PROCESS_CARD        322
#define IDC_CHK_AUTO_CREATE_FILE        323
#define IDC_CHK_DIM_PART_INFO           323
#define ID_BTN_CREATE_DRAWING           324
#define IDC_CHK_ANALYSIS_MAP            325
#define IDC_E_SEG_SCOPE                 328
#define IDC_CHK_SUM_DRAWING_MAP         329
#define IDC_CHK_STRU_DRAWING_MAP        330
#define IDC_E_BREAK_LINE_LEN            333
#define IDC_E_LEN_THRESHOLD             334
#define IDC_LIST_MODULE                 334
#define IDC_EDIT1                       335
#define IDC_E_LAYER_NAME                335
#define IDC_E_SPEC_PART_SERIALNO        335
#define IDC_E_TASK_NO                   335
#define IDC_E_RECT_L                    335
#define IDC_E_SPEC_WELDPART_CARD_PATHFILE 335
#define IDC_E_TID_FILE                  335
#define IDC_E_MIN_DISTANCE              335
#define IDC_E_LINE_WEIGHT               336
#define IDC_E_RECT_W                    336
#define IDC_CMB_LINETYPE                343
#define IDC_CMB_LINEWEIGHT              344
#define IDC_BTN_MOVE_BEFORE             345
#define IDC_E_MAP_FRAME_LENGTH          347
#define IDC_CHK_ARCPART                 347
#define IDC_E_MAP_FRAME_WIDTH           348
#define IDC_CHE_EDGE_NUM                348
#define IDC_E_MAP_FRAME_LEFT_MARGIN     349
#define IDC_E_MAP_FRAME_OTHERS_MARGIN   350
#define IDC_E_MAP_FRAME_BOTTOM_RIGHT_FIX_LEN 351
#define IDC_CHK_WELD_LENGTH             351
#define IDC_E_MAP_FRAME_BOTTOM_RIGHT_FIX_WIDTH 352
#define IDC_CHK_TRIAL_ASSEMBLY          352
#define IDC_E_MAP_FRAME_NAME            353
#define IDC_CHK_TASK_NO                 353
#define IDC_CHK_PATTERN_DRAW            354
#define IDC_CHK_TOLERANCE               354
#define IDC_LIST_TBL_ROW                355
#define IDC_S_TBL_ROW_TITLE             356
#define IDC_CMB_TOLERANCE               357
#define IDC_ANGLE_LIST                  357
#define IDC_CMB_LINE_WEIGHT             359
#define IDC_CHK_WELD_MARK               359
#define IDC_WORK_PANEL                  361
#define IDC_E_TEXT_H                    362
#define IDC_SCROLLBAR1                  363
#define IDC_S_TOWERTYPE                 364
#define IDC_CHK_INC_PROCESS_CARD        365
#define IDC_BN_DISPLAY_DETAILS_SETTING  366
#define IDC_CHK_LINE_MODEL              368
#define IDC_CHK_SOLID_MODEL             369
#define IDC_BTN_IMPORT_TID_FILE         370
#define IDC_S_ROW_OR_HORI               372
#define IDC_SIDC_S_COL_OR_VERT          373
#define IDC_S_COL_OR_VERT               374
#define IDC_S_ROLL_TYPE                 375
#define IDC_CMB_LENGTH_UNIT             376
#define IDD_SPECIAL_SETTING_DLG         528
#define IDC_INPUT_VAL_EDIT              1000
#define IDC_ARROW_ZOOM_WND              1000
#define IDC_E_LS_GUIGE                  1001
#define IDC_ARROW_ZOOM                  1001
#define IDC_VAR_PROMPT_STATIC           1002
#define IDC_ARROW_ROTATE                1002
#define IDC_MESSAGE_CONTENT_STATIC      1003
#define IDC_ARROW_PAN_MOVE              1003
#define IDC_ARROW_NORMAL                1004
#define IDC_DRAW_ARROW_CROSS            1005
#define IDC_ARROW_ARC                   1006
#define IDD_SET_BASE_GRID_STYLE_DLG     1008
#define IDC_TALK_MESSAGE_STATIC         1009
#define IDD_MAP_SIZE_DIM_DLG            1009
#define IDC_E_PART_MAP_SCALE            1010
#define IDD_SEL_PART_GROUP_DLG          1010
#define IDC_E_JG_ODDMENT                1011
#define IDC_E_AXIS_LINE                 1011
#define IDD_SPECIAL_PROCESS_STAT_CARD_DLG 1011
#define IDC_E_DIM_TEXT                  1012
#define IDC_E_HUOQU_LINE                1012
#define IDD_LOAD_ARROW_LOCATE_DLG       1012
#define IDC_E_A                         1013
#define IDC_E_LS_HOLE                   1013
#define IDC_E_OTHER_TEXT                1013
#define IDD_BOM_CFG_DLG                 1013
#define IDC_E_DIM_ARROW                 1014
#define IDC_E_P                         1014
#define IDC_E_DIM                       1014
#define IDC_E_DIM_SIMTRI                1014
#define IDC_E_HEADER_TEXT               1015
#define IDC_CMB_DATA_CONTENT            1015
#define IDC_E_DRAG_LINE                 1015
#define IDC_E_COMMON_TEXT               1016
#define IDC_E_NUMERIC_TEXT              1017
#define IDC_CMB_DATA_TYPE               1017
#define IDC_E_SIM_TRI_SCALE             1018
#define IDC_E_DIM_ANGLE_TEXT            1019
#define IDC_BN_EXPORT_ANALYZE_PROC_FILE 1019
#define IDC_LIST_CTRL                   1035
#define IDC_E_LINE_MAP_SCALE            1036
#define IDC_CHK_PARAM_TYPE_UEND         1036
#define IDC_E_STRU_MAP_SCALE            1037
#define IDC_CHK_PARAM_TYPE_ROLLEND      1037
#define IDC_CHK_PARAM_TYPE_FL           1038
#define IDC_E_FORCE_LINE_MAP_SCALE2     1038
#define IDC_E_FORCE_LINE_MAP_SCALE      1038
#define IDC_STRU_NUM                    1039
#define IDC_CHK_PARAM_TYPE_ELBOW        1039
#define IDC_CMB_STRU_NO                 1040
#define IDC_CHK_PLATE                   1040
#define IDC_CHK_PARAM_TYPE_CIRRIB       1041
#define IDC_CHK_PARAM_TYPE_CIRCOVER     1042
#define IDC_CHK_ANGLE                   1043
#define IDC_CHK_TRANSECT_TUBE           1044
#define IDC_DIMENSION_DRIECTION         1045
#define IDC_CHK_PARAM_TYPE_TUBERIB      1045
#define IDC_CHK_TUBE                    1045
#define IDC_ShuiPing                    1046
#define IDC_CHK_PARAM_TYPE_LINEANGLE_RIB 1046
#define IDC_CHK_SLOT                    1046
#define IDC_QingXie                     1047
#define IDC_QingXie2                    1048
#define IDC_E_SUM_VALUE                 1057
#define IDC_E_CHIEF_VALUE               1058
#define IDC_CMB_LEG_QUAD1               1058
#define IDC_CMB_LEG_QUAD_A              1058
#define IDC_E_SINGLE_MAP_COLOR_INDEX    1059
#define IDC_E_STRU_VALUE                1059
#define IDC_CMB_LEG_QUAD2               1059
#define IDC_CMB_LEG_QUAD_B              1059
#define IDC_R_LOCATE_POS                1060
#define IDC_E_PART_VALUE                1060
#define IDC_CMB_LEG_QUAD3               1060
#define IDC_CMB_LEG_QUAD_C              1060
#define IDC_RADIO2                      1061
#define IDC_E_WELD_VALUE                1061
#define IDC_CMB_LEG_QUAD4               1061
#define IDC_CMB_LEG_QUAD_D              1061
#define IDC_RADIO3                      1062
#define IDC_RADIO4                      1063
#define IDC_E_PART_CODE                 1067
#define IDC_S_TYPE                      1068
#define IDC_LIST_FACE_VERTEX            1069
#define IDC_BN_ADD_VERTEX               1070
#define IDC_LIST_VALID_ITEM             1071
#define IDC_S_PROMPT                    1072
#define IDC_S_DESCRIPTION               1073
#define IDC_CHK_DEFAULT_WORK_NORM       1074
#define IDC_S_CUR_PART                  1074
#define IDC_S_RED                       1074
#define IDC_BN_PASTE_WORK_NORM          1075
#define IDC_S_LIB_NAME                  1075
#define IDC_S_BLUE                      1075
#define IDC_E_NORM_X                    1076
#define IDC_E_NORM_Y                    1077
#define IDC_CHK_MODULATE_LONG_JG        1078
#define IDC_CHK_DIM_PLANK_OUTLINE       1079
#define IDC_CHK_JG_USE_SIMPLE_LS_MAP    1079
#define IDC_CHK_GEN_POLAR_COORD         1080
#define IDC_CHK_PLATE_USE_SIMPLE_LS_MAP 1080
#define IDC_CHK_GEN_DECARL_COORD        1081
#define IDC_DIM_PLANK_RAY_LS            1082
#define IDC_E_PART_ROWS_N               1083
#define IDC_E_LS_DIST_THRESHOLD         1084
#define IDC_CHK_DIM_PALNE_ANGLE         1084
#define IDC_E_ROW_HIGH                  1085
#define IDC_CHK_USE_ZHENG_FAN_QUN       1085
#define IDC_E_COLUMN_WIDTH              1086
#define IDC_E_POLE_X                    1087
#define IDC_E_LS_DIST_ZOOM_COEF         1087
#define IDC_CHK_HUOQU_TYPE              1087
#define IDC_E_POLE_Y                    1088
#define IDC_DIM_JG_G_AT_LEFT            1088
#define IDC_BN_DECARL_TO_POLAR          1089
#define IDC_BN_CPY_UCS                  1089
#define IDC_CHK_EXPORT_DEFORMED_PROFILE 1089
#define IDC_BN_POLAR_TO_DECARL          1090
#define IDC_BN_PASTE_UCS                1090
#define IDC_CHK_DIM_SPECIAL_END_SPACE   1091
#define IDC_BN_TO_RIGHT_HAND            1091
#define IDC_CHK_DIM_SPECIAL_LS_SPACE    1092
#define IDC_CHK_DIM_SPECIAL_JG_ZHUN     1093
#define IDC_E_VAL                       1093
#define IDC_CHK_DIM_LS_RAY_INFO         1094
#define IDC_E_MIN_WING_THICK            1095
#define IDC_E_USER_NAME                 1095
#define IDC_RDO_LS_APERTURE             1096
#define IDC_E_USER_PASSWORD             1096
#define IDC_E_PART_NO                   1097
#define IDC_RDO_LS_APERTURE2            1097
#define IDC_E_PART_GUIGE                1098
#define IDC_RDO_LS_APERTURE3            1098
#define IDC_E_MIN_WING_WIDE             1099
#define IDC_E_PART_NO_CIR_D             1099
#define IDC_E_NORM_Z                    1100
#define IDC_CHK_DIM_COORD               1100
#define IDC_E_X                         1101
#define IDC_SPIN_VISIBLE_OUTLINE        1101
#define IDC_CHK_ONE_CARD_MULTI_PART     1101
#define IDC_E_Y                         1102
#define IDC_SPIN_SINGLE_LINE            1102
#define IDC_CHK_ONE_CARD_FRAME          1102
#define IDC_BNT_SET_PATH                1102
#define IDC_SPIN_AXIS_LINE              1103
#define IDC_E_PART_DRAWING_PATH         1103
#define IDC_SPIN_HUOQU_LINE             1104
#define IDC_E_VISIBLE_OUTLINE           1105
#define IDC_E_SINGLE_LINE               1106
#define IDC_E_RADIUS                    1106
#define IDC_E_DASH_LINE                 1107
#define IDC_E_WIDTH                     1107
#define IDC_SPIN_DASH_LINE              1108
#define IDC_SPIN_DRAG_LINE              1109
#define IDC_E_PRJ_NAME                  1110
#define IDC_SPIN_LS_HOLE                1111
#define IDC_E_TA_TYPE                   1111
#define IDC_SPIN_DIM                    1112
#define IDC_E_TA_NUM                    1112
#define IDC_E_TA_ALIAS                  1113
#define IDC_E_TA_MAP_NO                 1114
#define IDC_E_TA_STAMP_NO               1114
#define IDC_E_TABLE_MAKER               1115
#define IDC_E_CRITIC                    1116
#define IDC_E_AUDITOR                   1117
#define IDC_E_COMPANY_NAME              1118
#define IDC_BTN_ADD_SETUP_AIDED_PLATE   1127
#define IDC_BTN_MODIFY_SETUP_AIDED_PLATE 1128
#define IDC_LIST_SUMTAMAT               1128
#define IDC_LIST_SUMTAMAT2              1129
#define IDC_LIST_PART                   1129
#define IDC_LIST_BOLT                   1130
#define IDC_CMB_TYPE                    1154
#define IDC_CMB_LEG_NO                  1161
#define IDC_E_LEG_NAME                  1162
#define IDC_BN_PASTE_AXIS_X             1174
#define IDC_E_AXIS_X_X                  1175
#define IDC_E_AXIS_X_Y                  1176
#define IDC_E_AXIS_X_Z                  1177
#define IDC_BN_PASTE_AXIS_Y             1178
#define IDC_E_AXIS_Y_X                  1179
#define IDC_E_AXIS_Y_Y                  1180
#define IDC_E_AXIS_Y_Z                  1181
#define IDC_BN_PASTE_AXIS_Z             1182
#define IDC_E_AXIS_Z_X                  1183
#define IDC_E_AXIS_Z_Y                  1184
#define IDC_E_AXIS_Z_Z                  1185
#define IDC_PROGRESS_BAR                1185
#define IDC_BN_COPY_AXIS_X              1186
#define IDC_NUMERIC_PROC                1186
#define IDC_BN_COPY_AXIS_Y              1187
#define IDC_BN_COPY_AXIS_Z              1188
#define IDC_VERSION                     1190
#define IDC_BN_BY_XY                    1191
#define IDC_BN_BY_YZ                    1192
#define IDC_BN_BY_ZX                    1193
#define IDC_BN_PASTE_ORIGIN_POS         1194
#define IDC_JG_NUM                      1195
#define IDC_E_ORIGIN_POS_X              1195
#define IDC_PART_NUM                    1195
#define IDC_NODE_NUM                    1196
#define IDC_E_ORIGIN_POS_Y              1196
#define IDC_BODY_NUM                    1197
#define IDC_E_ORIGIN_POS_Z              1197
#define IDC_LEG_NUM                     1198
#define IDC_BN_COPY_ORIGIN_POS          1198
#define IDC_S_TITLE                     1211
#define IDC_E_SERVER_NAME               1269
#define IDC_CMD_LIST_SUPER              1284
#define IDC_CMD_LIST_COMMON             1285
#define IDC_CMB_MAP_FRAME_NAME          1285
#define IDC_E_ANGLE                     1355
#define IDC_E_START_PLATE_HALF_T        1356
#define IDC_E_END_PLATE_HALF_T          1357
#define IDC_E_SETUP_AIDED_PLATE_PARTNO  1358
#define IDC_E_PROFILE_STYLE             1359
#define IDC_CMB_MODULE_NO               1391
#define IDC_S_KEY                       1419
#define IDC_S_PASSWORD                  1420
#define IDC_CMB_PLANK_AREA_STAT_TYPE    1444
#define IDC_CHK_ENABLE_AXIS_X           1466
#define IDC_CHK_ENABLE_AXIS_Y           1467
#define IDC_CHK_PROCESS_CARD_TBL        1468
#define IDC_CHK_ENABLE_AXIS_Z           1468
#define IDC_BN_CREATE_SELECTED_ITEMS    1469
#define IDD_OPTIMAL_SORT_DLG            1470
#define IDC_JG_LIST                     1470
#define IDC_CHE_JG                      1471
#define IDC_CHE_YG                      1472
#define IDC_CHE_TUBE                    1473
#define IDC_CHE_FLAT                    1474
#define IDC_CHE_JIG                     1475
#define IDC_CHE_GGS                     1476
#define IDC_CHE_Q345                    1477
#define IDC_CHE_Q235                    1478
#define IDC_CHE_Q390                    1479
#define IDC_CHE_Q420                    1480
#define IDC_CHE_Q460                    1481
#define IDD_RECONNECTION_SERVER_DLG     1482
#define IDC_E_THICK                     1483
#define IDC_E_NUM                       1484
#define IDD_UPLOAD_PROCESS_CARD_DLG     6004
#define IDD_SELECT_TOWER_TYPE           6005
#define IDC_E_CARD_PATH                 6018
#define IDC_CMB_TOWERTYPE_NAME          6018
#define IDC_BTN_JG_CARD                 6019
#define IDC_S_CARD                      6022
#define IDC_S_PROMPT_INFO               6024
#define IDC_CMB_PROJECT_NAME            6025
#define ID_LOAD_SCRIPT                  32773
#define ID_SAVE_SCRIPT                  32774
#define ID_SAVE_AS                      32775
#define ID_CLOSE                        32776
#define ID_START_SCRIPT                 32777
#define ID_ADD_BREAK_POINT              32778
#define ID_PREV_STEP                    32779
#define ID_NEXT_STEP                    32780
#define ID_STOP_SCRIPT                  32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON32822                  32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON32823                  32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON32824                  32784
#define ID_BUTTON32785                  32785
#define ID_BUTTON32825                  32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32826                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32827                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32828                  32788
#define ID_BUTTON32789                  32789
#define ID_ENABLE_ALL_ITEM              32789
#define ID_BUTTON32790                  32790
#define ID_DISABLE_ALL_ITEM             32790
#define ID_BUTTON32791                  32791
#define ID_NEW_ITEM                     32791
#define ID_BUTTON32792                  32792
#define ID_DELETE_ITEM                  32792
#define ID_BUTTON32793                  32793
#define ID_ADD_ITEM                     32793
#define ID_BUTTON32794                  32794
#define ID_REBULID_ITEM                 32794
#define ID_BUTTON32795                  32795
#define ID_ENABLE_SELECTED_ITEM         32795
#define ID_BUTTON32796                  32796
#define ID_DISABLE_SELECTED_ITEM        32796
#define ID_BUTTON32797                  32797
#define ID_IMPORT_SCRIPT                32797
#define ID_BUTTON32798                  32798
#define ID_EXPORT_SCRIPT                32798
#define ID_BUTTON32799                  32799
#define ID_UPDATE_ITEM                  32799
#define ID_BUTTON32800                  32800
#define ID_NEW_TOWERBODY                32800
#define ID_BUTTON32801                  32801
#define ID_NEW_TOWERLEG                 32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32829                  32803
#define ID_BUTTON32804                  32804
#define ID_BUTTON32830                  32804
#define ID_BUTTON32805                  32805
#define ID_BUTTON32831                  32805
#define ID_BUTTON32806                  32806
#define ID_BUTTON32832                  32806
#define ID_BUTTON32807                  32807
#define ID_BUTTON32833                  32807
#define ID_BUTTON32808                  32808
#define ID_MOVE_AFTER                   32808
#define ID_BUTTON32809                  32809
#define ID_MOVE_BEFORE                  32809
#define ID_BUTTON32810                  32810
#define ID_ADJUST_DRAWING_SERIAL_NO     32810
#define ID_BUTTON32811                  32811
#define ID_BUTTON32812                  32812
#define ID_BUTTON32813                  32813
#define ID_ERASE_RELA_CAD_ENT           32813
#define ID_BUTTON32814                  32814
#define ID_BUTTON32815                  32815
#define ID_CREATE_ITEMS                 32815
#define ID_BUTTON32816                  32816
#define ID_BUTTON32817                  32817
#define ID_BUTTON32818                  32818
#define ID_BUTTON32819                  32819
#define ID_BUTTON32820                  32820
#define ID_BUTTON32821                  32821
#define ID_ADD_PART_ITEM                32822
#define ID_BUTTON40024                  40024
#define ID_BUTTON40026                  40026
#define ID_BUTTON40037                  40037
#define ID_BUTTON40038                  40038
#define ID_BUTTON40039                  40039
#define ID_BUTTON40040                  40040
#define ID_BUTTON40042                  40042
#define ID_MOVE_TOP                     40051
#define ID_MOVE_BOTTOM                  40052
#define ID_MOVE_UP                      40053
#define ID_BUTTON40056                  40056
#define ID_BUTTON40057                  40057
#define ID_MOVE_DOWN                    40059
#define ID_BUTTON40086                  40086
#define ID_BUTTON40087                  40087
#define ID_BUTTON40202                  40202
#define ID_BUTTON40203                  40203
#define ID_BUTTON40209                  40209
#define ID_BUTTON40210                  40210
#define ID_BUTTON40223                  40223
#define ID_REVERSE_ANGLE                40224

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        277
#define _APS_NEXT_COMMAND_VALUE         32823
#define _APS_NEXT_CONTROL_VALUE         377
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
